apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  namespace: metallb-system
  name: gateway
spec:
  addresses:
    - 10.89.0.30/32
  serviceAllocation:
    namespaces:
      - cilium-system
