---
apiVersion: v1
kind: Namespace
metadata:
  name: intern-NUM
  labels:
    pod-security.kubernetes.io/audit-version: v1.28
    pod-security.kubernetes.io/audit: baseline
    pod-security.kubernetes.io/enforce-version: v1.28
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/warn-version: v1.28
    pod-security.kubernetes.io/warn: baseline
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: intern-NUM
  name: intern-NUM
subjects:
  - kind: Group
    name: intern-members@bacchus.snucse.org
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: intern-NUM
  name: intern-NUM
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: intern-NUM
      app.kubernetes.io/instance: intern-NUM
  template:
    metadata:
      labels:
        app.kubernetes.io/name: intern-NUM
        app.kubernetes.io/instance: intern-NUM
    spec:
      containers:
        - name: app
          image: nginx:latest
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 128Mi
          readinessProbe:
            httpGet:
              port: http
          livenessProbe:
            httpGet:
              port: http
---
apiVersion: v1
kind: Service
metadata:
  namespace: intern-NUM
  name: intern-NUM
spec:
  selector:
    app.kubernetes.io/name: intern-NUM
    app.kubernetes.io/instance: intern-NUM
  ports:
    - name: http
      port: 80
      targetPort: http
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  namespace: intern-NUM
  name: intern-NUM-practice
spec:
  parentRefs:
    - namespace: cilium-system
      name: web-gateway
      sectionName: https-bacchus-io
  hostnames:
    - practice.bacchus.io
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /intern-NUM/
      backendRefs:
        - name: practice
          port: 80
