---
apiVersion: v1
kind: Namespace
metadata:
  name: intern-NUM
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: intern-NUM
  name: intern-NUM
subjects:
  - kind: Group
    name: intern-members@bacchus.snucse.org
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
