---
apiVersion: v1
kind: Namespace
metadata:
  name: intern-NUM
  labels:
    pod-security.kubernetes.io/audit-version=v1.28
    pod-security.kubernetes.io/audit=baseline
    pod-security.kubernetes.io/enforce-version=v1.28
    pod-security.kubernetes.io/enforce=baseline
    pod-security.kubernetes.io/warn-version=v1.28
    pod-security.kubernetes.io/warn=baseline
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: intern-NUM
  name: intern-NUM
subjects:
  - kind: Group
    name: intern-members@bacchus.snucse.org
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
