---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argo
  name: bentley-gpu-controller
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: bacchus-gpu-controller
    server: 'https://147.46.92.213:6443'
  source:
    repoURL: https://bacchus-snu.github.io/bacchus-gpu-controller/
    targetRevision: 0.5.2
    chart: bacchus-gpu
    helm:
      values: |
        controller: {}
        admission:
          configs:
            oidc_username_prefix: "oidc:"
            default_role_name: "edit"
            authorized_group_names:
              - "oidc:bacchus"
              - "oidc:graduate"
              - "oidc:bentley-users"
        synchronizer:
          configs:
            gpu_server_name: "bentley"
            google_service_account_json_secret_name: "google-service-account-json"
            google_file_id: "16Q77VTnZgCytlWHEEEFIefV1SmLtAJbODa551P8y-yE"
            sync_interval_secs: 60

  project: bentley
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
