---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argo
  name: bentley-cert-manager
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cert-manager
    server: 'https://147.46.92.213:6443'

  source:
    repoURL: https://charts.jetstack.io
    targetRevision: v1.12.0
    chart: cert-manager
    helm:
      values: |
        installCRDs: true

  project: bentley
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
