---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argo
  name: bentley-sealed-secrets
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    server: 'https://147.46.92.213:6443'

  source:
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.11.0
    chart: sealed-secrets
    helm:
      values: |
        fullnameOverride: sealed-secrets-controller

  project: bentley
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
