---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argo
  name: ferrari-harbor
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: harbor
    server: 'https://147.46.15.75:6443'
  source:
    repoURL: https://helm.goharbor.io
    targetRevision: 1.12.3
    chart: harbor
    helm:
      values: |
        updateStrategy:
          type: Recreate
        expose:
          tls:
            certSource: secret
            secret:
              secretName: "harbor-ingress-tls"
          ingress:
            hosts:
              core: "registry.ferrari.snucse.org"
            className: nginx
            harbor:
              annotations:
                cert-manager.io/cluster-issuer: "letsencrypt-prod"
        externalURL: "https://registry.ferrari.snucse.org:30443"
        persistence:
          persistentVolumeClaim:
            registry:
              size: 500Gi
        trivy:
          enabled: false
        notary:
          enabled: false

  project: ferrari
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
