apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: metallb
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  destination:
    name: in-cluster
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    # Patched by metallb
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
  sources:
    - repoURL: https://metallb.github.io/metallb
      targetRevision: 0.13.12
      chart: metallb
      helm:
        values: |-
          speaker:
            tolerateMaster: false
