---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: vault
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  destination:
    name: in-cluster
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sources:
    - repoURL: https://helm.releases.hashicorp.com
      targetRevision: 0.26.0
      chart: vault
      helm:
        values: |-
          server:
            resources:
              requests:
                memory: 256Mi
                cpu: 250m
              limits:
                memory: 256Mi
                cpu: 250m

            auditStorage:
              enabled: true

          ui:
            enabled: true

          injector:
            enabled: false
          speaker:
            tolerateMaster: false
