apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: waiter-docs
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  destination:
    name: in-cluster
    namespace: waiter-docs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: ghcr.io/bacchus-snu
    chart: waiter-docs
    targetRevision: '20231103'
    helm:
      values: |-
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 64Mi
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  namespace: waiter-docs
  name: waiter-docs
spec:
  parentRefs:
    - namespace: cilium-system
      name: web-gateway
      sectionName: https-bacchus-io
  hostnames:
    - secure-front.bacchus.io
    - waiter.bacchus.io
  rules:
    - backendRefs:
        - name: waiter-docs
          port: 80
