server:
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 256Mi
      cpu: 250m

  auditStorage:
    enabled: true

ui:
  enabled: true

injector:
  enabled: false
speaker:
  tolerateMaster: false

