---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argo
  name: cert-manager
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cert-manager
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://charts.jetstack.io' 
    targetRevision: 1.9.1
    chart: cert-manager
    helm:
      values: |
        installCRDs: true
  project: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
